baseURL = "https://winadmins.io/"
languageCode = "en-us"
title = "WinAdmins Community"
theme = "hello-friend-ng"
disableKinds = ["RSS"]

[Author]
  name = "WinAdmins Community"

[params]
  dateform        = "2016-Jan-02"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  disableReadOtherPosts = true
  enableSharingButtons = true

  footerLeft = "Powered by <a href=\"https://gohugo.io\">Hugo</a>"
  footerRight = "Theme by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"

  customCSS = ["css/overrides.css"]

[params.logo]
  logoMark     = ""
  logoText     = "$WinAdmins"
  logoHomeLink = "/"

[[menu.main]]
  name       = "Discord"
  url        = "https://discord.com/invite/winadmins"
  weight     = 1

[[menu.main]]
  name       = "About Us"
  url        = "about-us"
  weight     = 2

[[menu.main]]
  name       = "Wiki"
  url        = "wiki"
  weight     = 3

[[menu.main]]
  name       = "Blog"
  url        = "blog"
  weight     = 4

[[menu.main]]
  name       = "Guidelines"
  url        = "guidelines"
  weight     = 5

[[menu.main]]
  name       = "Rules"
  url        = "rules"
  weight     = 6

[[menu.main]]
  name       = "Resources"
  url        = "resources"
  weight     = 7

[[menu.main]]
  name       = "Events"
  url        = "events"
  weight     = 8

[[menu.main]]
  name       = "Help"
  url        = "help"
  weight     = 9
